Add double pill prompt for PS2

diff --git a/dotbash_profile b/dotbash_profile
--- a/dotbash_profile
+++ b/dotbash_profile
@@ -110,11 +110,16 @@ source_files ~/.aliases \
 
 # this must come after git-completion.bash has been sourced
 # turn on path completion for go
+#
+# There's a way to trap error exit status and change your prompt based on that;
+# since my CMM prompt is a pill (U+1F48A, 💊 ), a good emoji for that might be
+# the syringe (U+1F489, 💉 )
 complete -o default -o nospace -F _git_checkout go
 
 if command -v ps1_set >/dev/null 2>&1 ; then
     # ps1_set --prompt ∫
     ps1_set --prompt "💊­"
+    export PS2=💊💊­
 else
     export PS1="!!! It's \D{%H} O'Clock! Time to install rvm to fix your prompt!\n$ "
 fi
